const fs = require('fs');
const path = require('path');

const mainJsPath = path.join(__dirname, 'src', 'main.js');
let mainJsContent = fs.readFileSync(mainJsPath, 'utf8');

const zhNetworkDict = `
    network: {
      nodeManagement: '节点管理',
      nodeAllocation: '节点分配',
      domainFilter: '域名过滤',
      domainDirect: '域名直连',
      privateNic: '私有网卡',
      publicNic: '公有网卡',
      usageGuide: '使用说明',
      macvlanHint: 'MacVlan由于网卡混杂模式工作原理，不支持无线网卡，必须使用有线网络连接才可正常工作。',
      nodeManagementList: '节点管理列表',
      searchGroup: '搜索分组',
      selectedNodes: '已选节点',
      batchDeleteNodes: '批量删除节点',
      batchSpeedTest: '批量测速',
      type: '类型',
      alias: '别名',
      address: '地址',
      port: '端口',
      protocol: '协议',
      latency: '延迟',
      deviceList: '设备列表',
      assignVpc: '分配节点',
      addGroup: '添加分组',
      addDomain: '添加域名',
      addRule: '添加规则',
      batchClearVpc: '批量清空',
      clearDirect: '清空直连',
      clearFilter: '清空过滤',
      clearVpc: '清空节点',
      closeDns: '关闭DNS',
      closeDnsWhitelist: '白名单模式',
      createNic: '创建网卡',
      deleteGroup: '删除分组',
      deleteGroupNode: '删除',
      directDomain: '直连域名',
      domainRuleDesc: '域名匹配规则',
      domainRules: '域名规则',
      editGroupAlias: '编辑别名',
      filterDomain: '过滤域名',
      fullRuleDesc: '完整匹配规则',
      gateway: '网关',
      globalRules: '全局规则',
      index: '序号',
      keywordRuleDesc: '关键字匹配',
      machineIP: '云机IP',
      machineName: '云机名称',
      nicName: '网卡名称',
      nodeName: '节点名称',
      noDomainDirectRules: '暂无直连规则',
      noDomainRules: '暂无域名规则',
      noPublicNicData: '暂无公有网卡数据',
      noVpcContainers: '暂无容器',
      openDns: '开启DNS',
      privateNicDesc: '私有网卡（VPC网络）说明',
      privateNicDescDetail: '私有网络会在宿主机创建一个独立的虚拟网关，并为云机分配在该虚拟局域网内的内部 IP，用来隔离或桥接外部网络代理。',
      privateNicList: '私有网卡列表',
      publicNicDesc: '公有网卡（MacVlan）说明',
      publicNicDescDetail: '公有网卡会将云机的通讯接口直接绑定并透传到真实局域网，使云机能拿到你所处真实局域网内的 IP 地址。',
      queryContainerDomainDirect: '查询容器域名直连',
      queryContainerDomainFilter: '查询容器域名过滤',
      queryGlobalDomainFilter: '查询全局域名过滤',
      selectContainer: '选择容器',
      selectContainerOrQuery: '选择容器并配置',
      selectContainerToQuery: '选择容器进行查询',
      selectDeviceFirst: '请先选择左侧设备',
      selectVpcContainer: '选择 VPC 容器',
      setContainerDomainFilter: '设置容器域名过滤',
      setDomainDirect: '设置域名直连',
      setGlobalDomainFilter: '设置全局域名过滤',
      sourceGroup: '源分组',
      speedTest: '测速',
      updateGroup: '更新分组',
      updateMacVlan: '更新 MacVlan',
      updateMacVlanTitle: '更新 MacVLAN 配置',
      vpcNodes: 'VPC节点'
    },`;

const enNetworkDict = `
    network: {
      nodeManagement: 'Node Management',
      nodeAllocation: 'Node Allocation',
      domainFilter: 'Domain Filter',
      domainDirect: 'Domain Direct',
      privateNic: 'Private NIC',
      publicNic: 'Public NIC',
      usageGuide: 'Usage Guide',
      macvlanHint: 'Due to the promiscuous mode mechanism, MacVlan does not support wireless network cards. A wired network connection is strictly required.',
      nodeManagementList: 'Node Management List',
      searchGroup: 'Search Group',
      selectedNodes: 'Selected Nodes',
      batchDeleteNodes: 'Batch Delete Nodes',
      batchSpeedTest: 'Batch Speed Test',
      type: 'Type',
      alias: 'Alias',
      address: 'Address',
      port: 'Port',
      protocol: 'Protocol',
      latency: 'Latency',
      deviceList: 'Device List',
      assignVpc: 'Assign Node',
      addGroup: 'Add Group',
      addDomain: 'Add Domain',
      addRule: 'Add Rule',
      batchClearVpc: 'Batch Clear',
      clearDirect: 'Clear Direct',
      clearFilter: 'Clear Filter',
      clearVpc: 'Clear Node',
      closeDns: 'Close DNS',
      closeDnsWhitelist: 'Whitelist Mode',
      createNic: 'Create NIC',
      deleteGroup: 'Delete Group',
      deleteGroupNode: 'Delete',
      directDomain: 'Direct Domain',
      domainRuleDesc: 'Domain Match Profile',
      domainRules: 'Domain Rules',
      editGroupAlias: 'Edit Alias',
      filterDomain: 'Filter Domain',
      fullRuleDesc: 'Full Match Profile',
      gateway: 'Gateway',
      globalRules: 'Global Rules',
      index: 'Index',
      keywordRuleDesc: 'Keyword Match',
      machineIP: 'Machine IP',
      machineName: 'Machine Name',
      nicName: 'NIC Name',
      nodeName: 'Node Name',
      noDomainDirectRules: 'No Direct Rules',
      noDomainRules: 'No Domain Rules',
      noPublicNicData: 'No Public NIC Data',
      noVpcContainers: 'No Containers',
      openDns: 'Open DNS',
      privateNicDesc: 'Private NIC (VPC Network) Desc',
      privateNicDescDetail: 'Creates an isolated virtual gateway on the host allocating internal IPs for machines to isolate traffic or bridge to proxy nodes.',
      privateNicList: 'Private NIC List',
      publicNicDesc: 'Public NIC (MacVlan) Desc',
      publicNicDescDetail: 'Binds the cloud machine directly to the physical LAN, allowing it to obtain an IP address on your real local network router.',
      queryContainerDomainDirect: 'Query Container Direct',
      queryContainerDomainFilter: 'Query Container Filter',
      queryGlobalDomainFilter: 'Query Global Filter',
      selectContainer: 'Select Container',
      selectContainerOrQuery: 'Select Container to Set',
      selectContainerToQuery: 'Select Container to Query',
      selectDeviceFirst: 'Please select a device first',
      selectVpcContainer: 'Select VPC Container',
      setContainerDomainFilter: 'Set Container Domain Filter',
      setDomainDirect: 'Set Domain Direct',
      setGlobalDomainFilter: 'Set Global Domain Filter',
      sourceGroup: 'Source Group',
      speedTest: 'Speed Test',
      updateGroup: 'Update Group',
      updateMacVlan: 'Update MacVlan',
      updateMacVlanTitle: 'Update MacVLAN Config',
      vpcNodes: 'VPC Nodes'
    },`;

let insertCount = 0;
// Insert it right before `model: {`
mainJsContent = mainJsContent.replace(
  /    model: \{/g,
  function(match) {
    insertCount++;
    if (insertCount === 1) {
      return zhNetworkDict + '\n' + match;
    } else if (insertCount === 2) {
      return enNetworkDict + '\n' + match;
    }
    return match;
  }
);

fs.writeFileSync(mainJsPath, mainJsContent);
console.log('SUCCESS: Injected network dicts');
